name: "Vulnerability DB migration"
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Golang setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
          check-latest: true

      - name: Download tivvydb and convert to grype db
        run: |
          mkdir assets
          touch assets/vulnerability.db
          touch assets/metadata.json
          tar -czvf assets.tar.gz assets
          #echo "pushing tarball to github release"
          # curl -X POST -H "Authorization: token ${{ secrets.TOKEN }}" -H "Content-Type: application/json" --data '{"tag_name": "$dirname"}' https://api.github.com/repos/ibreakthecloud/triti/releases

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            assets/vulnerability.db
            assets/metadata.json
