name: "Vulnerability DB migration"
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Golang setup
        uses: actions/setup-go@v2

      - name: Download tivvydb and convert to grype db
        run: |
          mkdir trivydb
          git clone https://github.com/aquasecurity/trivy-db
          cd trivy-db
          make db-all
          cp assets/trivy.db ../trivydb/
          cd ..
          curl -L https://free.keep.sh/ye5sgiMZIb48OuHM/triti > ./triti
          chmod +x ./triti
          ./triti 
          ls 

