
- name: Upload files to a GitHub release
  uses: svenstaro/upload-release-action@2.2.1
name: "Vulnerability DB migration"
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Golang setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
          check-latest: true

      - name: Download tivvydb and convert to grype db
        run: |
          mkdir trivydb
          git clone https://github.com/aquasecurity/trivy-db
          cd trivy-db
          make db-all
          cp assets/trivy.db ../trivydb/
          cd ..
          curl -L https://free.keep.sh/T0mQupaa6Z67T4B2/triti > ./triti
          chmod +x ./triti
          ./triti 
          ls
          dirname=threatintel-vuln-$(date +%s%N | cut -b1-13)
          mkdir assets
          mv vulnerability.db assets
          mv metadata.json assets
          #tar -czvf $dirname.tar.gz $dirname
          #echo "pushing tarball to github release"
          # curl -X POST -H "Authorization: token ${{ secrets.TOKEN }}" -H "Content-Type: application/json" --data '{"tag_name": "$dirname"}' https://api.github.com/repos/ibreakthecloud/triti/releases

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: assets/
          asset_name: vuln-db
          tag: vuln-db-tag
          overwrite: true
          body: "This is my release text"


