name: "Vulnerability DB migration"
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: Golang setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
          check-latest: true
        
      - name: make dir
        run: |
          echo "commit-id" > listing.json

      - name: Commit and push changes
        run: |
          ls
          git config --global user.name "Harshvardhan Karn"
          git config --global user.email "harshvardhan@deepfence.io"
          git add -A
          git commit -m "Auto-update listing $DATE"
          git push


